FROM rocker/r-ver:4.4.1

# System library dependency for the app
RUN apt-get update && apt-get install --no-install-recommends -y \
    # Version control
    git \
    # {httpuv} package requirement
    libz-dev \
    # {curl} package requirement
    libcurl4-openssl-dev \
    # {xlm2} package requirement
    libxml2-dev \
    # {terra} package requirements
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    libsqlite3-dev \
    # {httpgd} package requirement (VS Code development package)
    libfontconfig1-dev \
    # Open Shiny app in VS Code Viewer
    xdg-utils \
&& rm -rf /var/lib/apt/lists/*

# Pin renv version
ENV RENV_VERSION 1.0.7
RUN R -q -e "options(warn=2); install.packages('remotes')"
RUN R -q -e "options(warn=2); remotes::install_version('renv', '${RENV_VERSION}')"
